server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/DigitalMoneyHouse/protocol/openid-connect/auth 
            userinfo-uri: http://localhost:9090/realms/DigitalMoneyHouse/protocol/openid-connect/userinfo
            user-name-attribute: preferred-username
            token-uri: http://localhost:9090/realms/DigitalMoneyHouse/protocol/openid-connect/token
        registration:
          client1:
            provider: keycloak
            client-id: client1
            client-secret: LL0tbHYNV0h1kXydGoPwwANZy6zcsamV
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/client1
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service/
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: account-service
          uri: lb://account-service/
          predicates:
            - Path=/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: card-service
          uri: lb://card-service/
          predicates:
            - Path=/cards/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: transaction-service
          uri: lb://transaction-service/
          predicates:
            - Path=/transaction/**
          filters:
            - RemoveRequestHeader=Cookie
